[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"


[[menus.main]]
name = 'About'
url = '/'
weight = 10

[[menus.main]]
name = 'Publications'
url = '/publications'
weight = 20

[[menus.main]]
name = 'Posts'
url = '/posts'
weight = 30